require 'asciidoctor'

input = "index.adoc"
output = "index.html"
backend = "html5"

guard 'shell' do
  watch(input) {|m|
    system("asciidoctor" + " -b " + backend +  " -o " + output + " " + input)
  }
end
